### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by antofthy** [avih/dejsonlz4#1]
Thank you  Avi Halachmi

Could you include in your source code "README.md" file, links back to the firefox bug pages, as well as a link to the GIT HUB source.  This lets people who come across the code later to locate the code's primary source and the reasons for its existence.

**Comment by avih** [comment]
Good idea. I'll release a minor version with these updates soon. Thanks.

**Comment by avih** [comment]
Please review before I release an update: https://github.com/avih/dejsonlz4/blob/master/README.md

**Comment by antofthy** [comment]
Better.  Thanks.

**Comment by avih** [comment]
It's customary to close an issue only after it has been resolved, but I have not yet released the update ;)

(That's OK, keep it closed, I'll probably create the update tomorrow).

**Comment by avih** [comment]
Published the updated version. Thanks.
