### ISSUE TITLE
compressing back to mozlz4 format

### ISSUE THREAD

**Issue by pwlin** [avih/dejsonlz4#3]
Thanks for this great utility!
I use it to decompress `search.json.mozlz4` and modify my search providers. 
But is there any tool to compress my modified `search.json` back to its original `mozlz4` format so I can use it again?

**Comment by avih** [comment]
https://github.com/avih/dejsonlz4/tree/master/src/ref_compress

**Comment by pwlin** [comment]
ah ok I didn't see that. Thanks again.
