### ISSUE TITLE
Create jsonlz4?

### ISSUE THREAD

**Issue by JohnTHaller** [avih/dejsonlz4#8]
Any chance you could update this to also create the files? The oddball format Mozilla uses is oddly difficult to create with the standard tools unless I'm reading the header creation code incorrectly. I'd be happy to make a donation to you or a selected charity and/or credit you in the update announcement for the feature as it would help out a ton of users of PortableApps.com using both Firefox and Thunderbird from cloud drives and external drives between multiple PCs.

**Comment by avih** [comment]
It's been there all along https://github.com/avih/dejsonlz4/tree/master/src/ref_compress
