### ISSUE TITLE
Error unsupported file format

### ISSUE THREAD

**Issue by JordyC123** [avih/dejsonlz4#9]
Hi Avi,

I recently recovered some bookmarks that I lost. I lost them because I formatted the HDD and installed data over the top but did still manage to find all of the files. When using your tool, I got the Error: unsupported file format message. Is that because my data is corrupt or because I did something wrong?

Just to be clear, I put the bookmark backup file into the same folder as the .exe. Then opened Powershell in the same folder and typed desjonlz4.exe booksmarkfilename.jsonlz4, then hit enter.

Is that the correct way to use it? Sorry, I'm a bit of a technical noob.

**Comment by avih** [comment]
> Error: unsupported file format

This error is printed when the file is too small to be valid, or if it doesn't contain the string which indicates it's the correct file type - https://github.com/avih/dejsonlz4/blob/master/src/dejsonlz4.c#L131

So I'd say corrupted.
